### ISSUE TITLE
JEI Optimization Search Issue

### ISSUE THREAD

**Issue by reddvilzz** [LoliKingdom/LoliASM#41]
Hi there, I'm using version 4.1 and I found out when the JEI Optimization is enabled the search feature in JEI is a bit messed up, when I type for example, Speed Upgrade this will show up

without JEI Optimization

![image](https://user-images.githubusercontent.com/6846358/139516061-3ea0bafc-bdc2-4fb3-bffa-a8f1daf22626.png)

and the [log](https://gist.github.com/reddvilzz/883157b4ec7c05787aa26d8da56e1b90)

with JEI Optimization

![image](https://user-images.githubusercontent.com/6846358/139516799-c4a26eb5-1fd3-4165-9c26-727f55f27701.png)

[log](https://gist.github.com/reddvilzz/06e8cfe0252ba2e24b251a8756be8956)

as you can see it showing up different results, and when I tried searching for rubber it will show a bunch of unrelated results that don't even have the word rubber in it.

**Comment by reddvilzz** [comment]
It is fixed using 4.2.1, I didn't notice there's an update to it.

**Comment by reddvilzz** [comment]
Just found out, 4.2.1 fix it slightly but there are still some search parameters that doesn't show up when I try to find it.

**Comment by Rongmario** [comment]
@reddvilzz mind trying this experimental build?: [loliasm-4.2.2.zip](https://github.com/LoliKingdom/LoliASM/files/7446002/loliasm-4.2.2.zip)

**Comment by Z-Tunic** [comment]
So I'm not going crazy if it was due to me removing mods from my world and that breaking the JEI search... which a re-install of JEI or clearing the cache folder of the JEI stuff fixes it... until you reload the world then it messes up again.

In my case... I have Advent of Ascension installed along with some other mods and when typing in 'blaster' it should show all blasters + whatever else that has 'blaster' in the name/info from Advent of Ascension. Without doing the above it would show random blocks/items that aren't blasters whenever I type in 'blaster', much like in OP's post.

![SneedASMJEIOpBug](https://user-images.githubusercontent.com/36653806/139526999-25bdcbb2-96cd-457c-9f59-0c1aa987e7ac.png)
Most of those items don't have 'blaster' in their name/info, also... this can happen with other modded stuff, where 'Terrasteel' from Botania wouldn't show the right results at times.

At the moment it's 4am for me but I took a quick look at the experimental build and this is what I can see.

![SneedASMJEIOpMaybeFixed](https://user-images.githubusercontent.com/36653806/139527351-8e47e936-c56d-46e4-803b-3a7667e02037.png)
So 'blaster' shows up correctly as those items have the matching name/info. Unsure if it's fully fixed but I can give it another look when I wake up.

**Comment by reddvilzz** [comment]
> 
> 
> @reddvilzz mind trying this experimental build?: [loliasm-4.2.2.zip](https://github.com/LoliKingdom/LoliASM/files/7446002/loliasm-4.2.2.zip)

can confirm it seems like the experimental build fixed it. I'll report back after further testing if there are any search parameters that seems off.

**Comment by Rongmario** [comment]
Nice, hopefully that's the case.

**Comment by reddvilzz** [comment]
I'll close this for now.
